import type { RpcRequest } from '@solana/rpc-spec';

const SOLANA_RPC_METHODS: string[] = [
    'getAccountInfo',
    'getBalance',
    'getBlock',
    'getBlockCommitment',
    'getBlockHeight',
    'getBlockProduction',
    'getBlocks',
    'getBlocksWithLimit',
    'getBlockTime',
    'getClusterNodes',
    'getEpochInfo',
    'getEpochSchedule',
    'getFeeForMessage',
    'getFirstAvailableBlock',
    'getGenesisHash',
    'getHealth',
    'getHighestSnapshotSlot',
    'getIdentity',
    'getInflationGovernor',
    'getInflationRate',
    'getInflationReward',
    'getLargestAccounts',
    'getLatestBlockhash',
    'getLeaderSchedule',
    'getMaxRetransmitSlot',
    'getMaxShredInsertSlot',
    'getMinimumBalanceForRentExemption',
    'getMultipleAccounts',
    'getProgramAccounts',
    'getRecentPerformanceSamples',
    'getRecentPrioritizationFees',
    'getSignaturesForAddress',
    'getSignatureStatuses',
    'getSlot',
    'getSlotLeader',
    'getSlotLeaders',
    'getStakeActivation',
    'getStakeMinimumDelegation',
    'getSupply',
    'getTokenAccountBalance',
    'getTokenAccountsByDelegate',
    'getTokenAccountsByOwner',
    'getTokenLargestAccounts',
    'getTokenSupply',
    'getTransaction',
    'getTransactionCount',
    'getVersion',
    'getVoteAccounts',
    'index',
    'isBlockhashValid',
    'minimumLedgerSlot',
    'requestAirdrop',
    'sendTransaction',
    'simulateTransaction',
];

/**
 * Helper function that checks if a given `RpcRequest` comes from the Solana RPC API.
 */
export function isSolanaRequest(request: RpcRequest): boolean {
    return SOLANA_RPC_METHODS.includes(request.methodName);
}
